name: Publish Release

on:
  workflow_dispatch:

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          token: ${{ secrets.WSO2_INTEGRATION_BOT_TOKEN }}
          fetch-depth: 0
      - name: Set up JDK 11 with AdoptOpenJDK and Maven 3.6.3
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Specify the distribution (AdoptOpenJDK)
          java-version: '11'          # Specify the Java version you want to use
      - name: Uninstall Maven
        run: |
          sudo rm -rf /opt/maven           # Remove Maven directory
          sudo rm -f /usr/bin/mvn
      - name: Install Maven 3.6.3
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xvzf apache-maven-3.6.3-bin.tar.gz
          sudo mv apache-maven-3.6.3 /opt/maven
          sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
      - name: Extract project version
        run: |
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml | sed 's/-SNAPSHOT$//')
          VERSION_TAG="v$VERSION"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
      - name: Configure Maven settings file
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>releases</id>
                      <username>${{ secrets.NEXUS_USERNAME }}</username>
                      <password>${{ secrets.NEXUS_PASSWORD }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
      - name: mvn version
        run: |
          mvn -v
      - name: Configure git credentials
        run: |
          git config --global user.name ${{ secrets.WSO2_INTEGRATION_BOT_USERNAME }}
          git config --global user.email ${{ secrets.WSO2_INTEGRATION_BOT_EMAIL }}
      - name: Build artifacts
        run: |
          mvn clean install
      - name: Deploy artifacts with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.WSO2_INTEGRATION_BOT_TOKEN }}
        run: |
          mvn --batch-mode release:prepare release:perform -Dtag=${{ env.VERSION_TAG }}
      - name: Create Github Release with Assets
        env:
          GITHUB_TOKEN: ${{ secrets.WSO2_INTEGRATION_BOT_TOKEN }}
        run: |
          find target/ -type f -name '*-SNAPSHOT.zip' -exec rm -f {} \;
          gh release create "${{ env.VERSION_TAG }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${{ env.VERSION_TAG }}" \
            --generate-notes \
            target/*.zip
